### ISSUE TITLE
[Bug]: Both MdeModulePkg and IpmiFeaturePkg have IpmiCommandLib.h that may cause compatible issue

### ISSUE THREAD

**Issue by MarcChen46** [microsoft/mu_feature_ipmi#139]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

in "release/202302", both MdeModulePkg and IpmiFeaturePkg have IpmiCommandLib.h, and since the implementation is different between each other, if we want to include the library header file from IpmiFeaturePkg, then we need to adjust the order of package DEC file in INF.

### Expected Behavior

The Library class header file should only existed in one package to prevent compatible issue.

### Steps To Reproduce

Search the "IpmiCommandLib.h" file from all MU related sub-modules, and only MdeModulePkg should have it.

### Build Environment

```markdown
- OS(s): Windows 11
- Tool Chain(s): BS2022 
- Targets Impacted: RELEASE, DEBUG, NO-TARGET, NOOPT
```

### Version Information

```text
release/202302
```

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

Maintainer feedback requested

**Comment by apop5** [comment]
@MarcChen46 

Thanks for reporting this.

I believe the best course of action is to bring mu_feature_ipmi into compliance with the MdeModulePkg's IpmiCommandLib, and eliminate the header file that we are using in IpmiFeaturePkg.

Actions:
IpmiGetSystemUuid in MdeModulePkg, IpmiGetSystemGuid in Mu, just rename to match MdeModulePkg
IpmiGetChannelInfo doens't exist in Mu, create function
IpmiGetLanConfigurationParameters doesn't exist in Mu, create function


IpmiSetPowerRestorePolicy - Parameter names differ (ChassisControlRequest needs to become SetPowerRestireRequest, ChassisControlResponse -> SetPowerRestireResponse) (need to check in Edk2 why it is misspelled?)

IpmiSetSystemBootOptions - additional parameter RequestSize exists in Mu, try to eliminate additional parameter
IpmiGetSystemBootOptions - additional parameter ResponseSize exists in Mu, try to eliminate  additional parameter

IpmiGetSystemInterfaceCapabilities - Exists in mu, doesn't exist in MdeModulePkg. Add to MdeModulePkg
