### ISSUE TITLE
Add NULL Check as IpmiSendCommandInternal does not consider NULL parameter for ResponseData and ResponseDataSize Parameter 

### ISSUE THREAD

**Issue by anandakrishnanl** [microsoft/mu_feature_ipmi#242]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

 IpmiSendCommandInternal does not consider NULL parameter for ResponseData and ResponseDataSize Parameter 

### Expected Behavior

NULL can be passed as parameter for 

  IN OUT  UINT8           *ResponseData,
  IN OUT  UINT8           *ResponseDataSize

in IpmiSendCommandInternal  Routine

### Steps To Reproduce

Pass NULL for any IPMI send Command which will result in Exception

### Build Environment

```markdown
Windows 11
VS2019
NA
```

### Version Information

```text
https://azurecsi.visualstudio.com/MCUP/_git/Common/commit/d5fc34607f80751eba6d3d6a8dec86305ef0c228?refName=refs/heads/main
```

### Urgency

Medium

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

Maintainer feedback requested

### Anything else?

NULL Check Fix will be pushed to a branch and pull request will be created

**Comment by apop5** [comment]
Closed by #243
